spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/catalogue
    username: postgres
    password: qwe
  flyway:
    schemas:
      - public
      - catalogue
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/magazine
  jpa:
    show-sql: true
server:
  port: 8081
logging:
  level:
    sql: info